### ISSUE TITLE
When does "DomainEvents" turn into an "EventStream" for use in the EventStore?

### ISSUE THREAD

**Issue by ramondelafuente** [simple-es/event-sourcing#1]
When implementing `TracksEvents` and using `EventTrackingCapabilities`, the aggregate ends up with `DomainEvents`.

The Doctrine DBAL Bridge can save an `EventStream`.

I could use some help inderstanding how and where one is turned into the other...

**Comment by jaspernbrouwer** [comment]
You implement `TracksEvents` for an aggregate (root entity), which indeed tracks/records `DomainEvent`s.

When your business transaction is at an end, you can pass the Aggregate to the Repository (`Repository` or its implementation `AggregateRepository`), which will internally uses `WrapsEvents` to wrap the `DomainEvent`s in `EventEnvelope`s (thus converting `DomainEvents` into a `EventStream`).

The `EventStream` is the passed to `StoresEvents` to get stored.

PS: `StoresEvents` can be decorated to alter the `EventStream` (enrich its metadata for example).

**Comment by ramondelafuente** [comment]
All clear.
